apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-svc
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: catalog-svc
          resources:
            requests:
              cpu: 200m
              memory: 384Mi
            limits:
              cpu: 1000m
              memory: 768Mi