apiVersion: v1
kind: Service
metadata:
  name: payment-svc
  labels:
    app: payment-svc
    app.kubernetes.io/part-of: ecommerce-platform
spec:
  type: ClusterIP
  selector:
    app: payment-svc
  ports:
    - name: http
      port: 8085
      targetPort: http