apiVersion: v1
kind: Service
metadata:
  name: auth
  labels:
    app: auth
    app.kubernetes.io/part-of: ecommerce-platform
spec:
  type: ClusterIP
  selector:
    app: auth
  ports:
    - name: http
      port: 8080
      targetPort: http