apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkout-svc
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: checkout-svc
          resources:
            requests:
              cpu: 200m
              memory: 384Mi
            limits:
              cpu: 1000m
              memory: 768Mi