apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Base manifests for order-svc — environment-agnostic.
namespace: ecommerce

labels:
  - pairs:
      app.kubernetes.io/part-of: ecommerce-platform

resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - hpa.yaml
  - pdb.yaml
  - serviceaccount.yaml
  - networkpolicy.yaml

images:
  - name: acr.azurecr.io/order-svc
    newName: acr.azurecr.io/order-svc
    newTag: latest